FROM node:20-alpine

WORKDIR /opt/blog

COPY package.json package-lock.json ./

RUN npm install

CMD ["npx", "tailwindcss", "-i", "./static/css/tailwind.css", "-o", "./static/css/tailwind.compiled.css", "-w"]

# CMD tail -f /dev/null
